### ISSUE TITLE
Create end point for client request

### ISSUE THREAD

**Issue by Austinmc41** [Austinmc41/KADET#36]
The goal: Post request triggers a endpoint that calls a function on the server side; in order to to this we need a working end point

step 5 should cover how to add endpoints and API views

https://www.digitalocean.com/community/tutorials/how-to-build-a-modern-web-application-to-manage-customer-information-with-django-and-react-on-ubuntu-18-04

**Comment by ed209uardo** [comment]
endpoint successfully created
